"""SpaceCDF — Flight Software Mode Manager Generator.

Generates a compilable mode manager from ConOps operational modes.
Produces: mode enum, mode transition table, transition guard functions,
FDIR safe mode entry triggers, and a main mode manager loop.

Part of Stage 4: CubeSat full lifecycle capability.
"""
from __future__ import annotations

from typing import Any


def generate_mode_manager(
    modes: list[dict[str, Any]],
    fdir_rules: list[dict[str, Any]] | None = None,
) -> dict[str, str]:
    """Generate mode manager C source and header files.

    Args:
        modes: List of ConOps operational modes with power/pointing profiles
        fdir_rules: Optional FDIR rules for safe mode entry

    Returns:
        Dict of {filename: content} for the mode manager module.
    """
    fdir_rules = fdir_rules or []
    mode_names = [m.get("id", f"MODE_{i}").upper().replace("-", "_") for i, m in enumerate(modes)]

    # --- Header file ---
    header = f"""/**
 * @file mode_manager.h
 * @brief Spacecraft Mode Manager — auto-generated from SpaceCDF ConOps
 *
 * Generated by SpaceCDF Flight Software Generator
 * DO NOT EDIT — regenerate from ConOps if modes change
 */
#ifndef MODE_MANAGER_H
#define MODE_MANAGER_H

#include <stdint.h>
#include <stdbool.h>

/* Spacecraft operational modes */
typedef enum {{
{chr(10).join(f'    SC_MODE_{name} = {i},' for i, name in enumerate(mode_names))}
    SC_MODE_COUNT
}} sc_mode_t;

/* Mode descriptor */
typedef struct {{
    sc_mode_t   mode_id;
    const char* name;
    float       power_w;
    float       pointing_deg;
    bool        payload_active;
    bool        sun_required;
    bool        downlink_active;
}} mode_descriptor_t;

/* Mode transition */
typedef struct {{
    sc_mode_t from_mode;
    sc_mode_t to_mode;
    bool      (*guard_fn)(void);
    const char* description;
}} mode_transition_t;

/* Public API */
void         mode_manager_init(void);
sc_mode_t    mode_manager_get_current(void);
bool         mode_manager_request_transition(sc_mode_t target);
void         mode_manager_tick(void);
void         mode_manager_enter_safe_mode(const char* reason);
const mode_descriptor_t* mode_manager_get_descriptor(sc_mode_t mode);

/* FDIR callbacks — implement these in fdir_app.c */
extern bool fdir_check_power_ok(void);
extern bool fdir_check_comms_ok(void);
extern bool fdir_check_attitude_ok(void);
extern bool fdir_check_thermal_ok(void);

#endif /* MODE_MANAGER_H */
"""

    # --- Source file ---
    mode_table_entries = []
    for i, m in enumerate(modes):
        name = mode_names[i]
        mode_table_entries.append(
            f'    {{ SC_MODE_{name}, "{m.get("name", name)}", '
            f'{m.get("power_w", 0):.1f}f, '
            f'{m.get("pointing_requirement_deg", 5.0):.2f}f, '
            f'{"true" if m.get("payload_active", False) else "false"}, '
            f'{"true" if m.get("sun_illuminated", True) else "false"}, '
            f'{"true" if m.get("data_downlink_active", False) else "false"} }}'
        )

    # Generate transition table
    # Default: any mode can go to safe, safe can go to any mode
    transitions = []
    safe_idx = next((i for i, n in enumerate(mode_names) if "SAFE" in n), 0)
    for i, name in enumerate(mode_names):
        if i != safe_idx:
            transitions.append(f'    {{ SC_MODE_{name}, SC_MODE_{mode_names[safe_idx]}, NULL, "Emergency: {name} -> SAFE" }}')
            transitions.append(f'    {{ SC_MODE_{mode_names[safe_idx]}, SC_MODE_{name}, NULL, "Recovery: SAFE -> {name}" }}')

    # Adjacent mode transitions (nominal -> downlink -> nominal, etc.)
    for i in range(len(mode_names)):
        for j in range(len(mode_names)):
            if i != j and i != safe_idx and j != safe_idx:
                if abs(i - j) == 1:
                    transitions.append(f'    {{ SC_MODE_{mode_names[i]}, SC_MODE_{mode_names[j]}, NULL, "Nominal: {mode_names[i]} -> {mode_names[j]}" }}')

    # FDIR rules
    fdir_checks = []
    for rule in fdir_rules:
        trigger = rule.get("trigger", "unknown")
        action = rule.get("action", "safe_mode")
        fdir_checks.append(f"""
    /* FDIR: {rule.get('description', trigger)} */
    if (!fdir_check_{trigger}()) {{
        mode_manager_enter_safe_mode("{trigger} failure");
        return;
    }}""")

    if not fdir_checks:
        # Default FDIR checks
        fdir_checks = ["""
    /* Default FDIR checks */
    if (!fdir_check_power_ok()) {
        mode_manager_enter_safe_mode("Power subsystem anomaly");
        return;
    }
    if (!fdir_check_comms_ok()) {
        /* Comms loss — don't immediately safe mode, wait for timeout */
    }
    if (!fdir_check_attitude_ok()) {
        mode_manager_enter_safe_mode("Attitude control anomaly");
        return;
    }"""]

    source = f"""/**
 * @file mode_manager.c
 * @brief Spacecraft Mode Manager — auto-generated from SpaceCDF ConOps
 */
#include "mode_manager.h"
#include <stdio.h>
#include <string.h>

/* Mode descriptors */
static const mode_descriptor_t g_mode_table[SC_MODE_COUNT] = {{
{(',' + chr(10)).join(mode_table_entries)}
}};

/* Transition table */
static const mode_transition_t g_transitions[] = {{
{(',' + chr(10)).join(transitions)}
}};
static const int g_num_transitions = sizeof(g_transitions) / sizeof(g_transitions[0]);

/* Current mode */
static sc_mode_t g_current_mode = SC_MODE_{mode_names[safe_idx]};
static uint32_t  g_mode_entry_tick = 0;
static uint32_t  g_tick_count = 0;

void mode_manager_init(void) {{
    g_current_mode = SC_MODE_{mode_names[safe_idx]};
    g_mode_entry_tick = 0;
    g_tick_count = 0;
    printf("[MODE] Initialised in {mode_names[safe_idx]} mode\\n");
}}

sc_mode_t mode_manager_get_current(void) {{
    return g_current_mode;
}}

const mode_descriptor_t* mode_manager_get_descriptor(sc_mode_t mode) {{
    if (mode < SC_MODE_COUNT) return &g_mode_table[mode];
    return NULL;
}}

bool mode_manager_request_transition(sc_mode_t target) {{
    if (target >= SC_MODE_COUNT) return false;
    if (target == g_current_mode) return true;

    /* Check if transition is allowed */
    for (int i = 0; i < g_num_transitions; i++) {{
        if (g_transitions[i].from_mode == g_current_mode &&
            g_transitions[i].to_mode == target) {{
            /* Check guard function if present */
            if (g_transitions[i].guard_fn && !g_transitions[i].guard_fn()) {{
                printf("[MODE] Transition %s BLOCKED by guard\\n",
                       g_transitions[i].description);
                return false;
            }}
            printf("[MODE] Transition: %s -> %s (%s)\\n",
                   g_mode_table[g_current_mode].name,
                   g_mode_table[target].name,
                   g_transitions[i].description);
            g_current_mode = target;
            g_mode_entry_tick = g_tick_count;
            return true;
        }}
    }}
    printf("[MODE] Transition %d -> %d NOT ALLOWED\\n", g_current_mode, target);
    return false;
}}

void mode_manager_enter_safe_mode(const char* reason) {{
    printf("[FDIR] SAFE MODE ENTRY: %s\\n", reason);
    g_current_mode = SC_MODE_{mode_names[safe_idx]};
    g_mode_entry_tick = g_tick_count;
}}

void mode_manager_tick(void) {{
    g_tick_count++;
    {"".join(fdir_checks)}
}}
"""

    return {
        "src/mode_manager/mode_manager.h": header,
        "src/mode_manager/mode_manager.c": source,
    }


def generate_telemetry_definitions(
    parameters: dict[str, Any],
    spacecraft_name: str = "SC1",
) -> dict[str, str]:
    """Generate telemetry packet definitions from design parameters.

    Each domain becomes a TM packet with its parameters as fields.
    """
    domains: dict[str, list[tuple[str, str, str]]] = {}
    for pid, param in parameters.items():
        parts = pid.split(".")
        if len(parts) < 2:
            continue
        domain = parts[0]
        field_name = "_".join(parts[1:])
        unit = ""
        if hasattr(param, "unit"):
            unit = param.unit
        elif isinstance(param, dict):
            unit = param.get("unit", "")
        domains.setdefault(domain, []).append((field_name, pid, unit))

    header = f"""/**
 * @file tm_packets.h
 * @brief Telemetry packet definitions — auto-generated from SpaceCDF design
 *
 * {len(parameters)} parameters across {len(domains)} domains
 * Spacecraft: {spacecraft_name}
 */
#ifndef TM_PACKETS_H
#define TM_PACKETS_H

#include <stdint.h>

"""
    for domain, fields in sorted(domains.items()):
        struct_name = f"tm_{domain}_t"
        header += f"/* {domain.upper()} telemetry — {len(fields)} parameters */\n"
        header += f"typedef struct __attribute__((packed)) {{\n"
        header += f"    uint32_t timestamp_ms;\n"
        for fname, pid, unit in fields:
            header += f"    float    {fname};  /* {unit} — {pid} */\n"
        header += f"}} {struct_name};\n\n"

    # APID allocation
    header += "/* Application Process IDs (CCSDS) */\n"
    header += "typedef enum {\n"
    for i, domain in enumerate(sorted(domains.keys())):
        header += f"    APID_{domain.upper()} = {0x100 + i},\n"
    header += f"    APID_COUNT = {len(domains)}\n"
    header += "} apid_t;\n\n"

    header += "#endif /* TM_PACKETS_H */\n"

    # Telecommand definitions
    tc_header = f"""/**
 * @file tc_packets.h
 * @brief Telecommand definitions — auto-generated from SpaceCDF design
 */
#ifndef TC_PACKETS_H
#define TC_PACKETS_H

#include <stdint.h>

/* Mode commands */
typedef struct __attribute__((packed)) {{
    uint8_t  target_mode;
    uint8_t  confirmation;
}} tc_mode_change_t;

/* Parameter override */
typedef struct __attribute__((packed)) {{
    uint16_t param_id;
    float    new_value;
    uint8_t  source;  /* 0=ground, 1=onboard */
}} tc_param_override_t;

/* Payload control */
typedef struct __attribute__((packed)) {{
    uint8_t  payload_id;
    uint8_t  command;  /* 0=off, 1=on, 2=configure */
    float    parameter;
}} tc_payload_ctrl_t;

/* Telecommand IDs */
typedef enum {{
    TC_MODE_CHANGE     = 0x01,
    TC_PARAM_OVERRIDE  = 0x02,
    TC_PAYLOAD_CTRL    = 0x03,
    TC_SAFE_MODE       = 0x04,
    TC_REBOOT          = 0x05,
    TC_MEMORY_DUMP     = 0x06,
    TC_TIME_SYNC       = 0x07,
}} tc_id_t;

#endif /* TC_PACKETS_H */
"""

    return {
        "inc/tm_packets.h": header,
        "inc/tc_packets.h": tc_header,
    }


def generate_fdir_rules(
    reliability_data: dict[str, Any] | None = None,
    modes: list[dict] | None = None,
) -> dict[str, str]:
    """Generate FDIR (Fault Detection, Isolation, Recovery) rules.

    Based on subsystem reliability data and ConOps modes, generates
    fault detection checks and recovery actions.
    """
    source = """/**
 * @file fdir_rules.c
 * @brief FDIR Rules — auto-generated from SpaceCDF reliability analysis
 */
#include "mode_manager.h"
#include <stdbool.h>

/* Watchdog timers (seconds) */
#define WDT_COMMS_TIMEOUT_S     (3600 * 6)  /* 6 hours without ground contact */
#define WDT_ATTITUDE_TIMEOUT_S  300          /* 5 minutes of attitude loss */
#define WDT_POWER_LOW_V         6.0f         /* Battery undervoltage threshold */

static uint32_t g_last_ground_contact_s = 0;
static uint32_t g_attitude_loss_start_s = 0;

bool fdir_check_power_ok(void) {
    /* Check battery voltage above minimum */
    /* float vbat = eps_get_battery_voltage(); */
    /* return vbat > WDT_POWER_LOW_V; */
    return true;  /* Stub — implement with actual EPS telemetry */
}

bool fdir_check_comms_ok(void) {
    /* Check time since last ground contact */
    /* uint32_t elapsed = get_mission_time_s() - g_last_ground_contact_s; */
    /* return elapsed < WDT_COMMS_TIMEOUT_S; */
    return true;  /* Stub */
}

bool fdir_check_attitude_ok(void) {
    /* Check attitude determination is valid */
    /* return adcs_attitude_valid(); */
    return true;  /* Stub */
}

bool fdir_check_thermal_ok(void) {
    /* Check all temperatures within operating range */
    /* return thermal_all_in_range(); */
    return true;  /* Stub */
}

void fdir_update_ground_contact(void) {
    /* g_last_ground_contact_s = get_mission_time_s(); */
}
"""

    header = """/**
 * @file fdir_rules.h
 * @brief FDIR function declarations
 */
#ifndef FDIR_RULES_H
#define FDIR_RULES_H

#include <stdbool.h>

bool fdir_check_power_ok(void);
bool fdir_check_comms_ok(void);
bool fdir_check_attitude_ok(void);
bool fdir_check_thermal_ok(void);
void fdir_update_ground_contact(void);

#endif /* FDIR_RULES_H */
"""

    return {
        "src/fdir/fdir_rules.c": source,
        "src/fdir/fdir_rules.h": header,
    }
