"""SpaceCDF — DOCX Generator for Design Review Documents.

Uses python-docx to produce a Word document mirroring the Markdown template:
title, executive summary, system overview, mass/power/data budgets, cost
breakdown, compliance matrix, equipment list, TRL assessment.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Inches, Pt, RGBColor


STATUS_COLOURS = {
    "compliant": "C6EFCE",
    "green": "C6EFCE",
    "marginal": "FFEB9C",
    "amber": "FFEB9C",
    "non_compliant": "FFC7CE",
    "red": "FFC7CE",
    "exceeded": "FFC7CE",
}


def _shade_cell(cell, hex_colour: str) -> None:
    """Apply a background fill colour to a table cell."""
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_colour)
    tc_pr.append(shd)


def _add_header_row(table, headers: list[str]) -> None:
    hdr = table.rows[0].cells
    for i, h in enumerate(headers):
        hdr[i].text = h
        for run in hdr[i].paragraphs[0].runs:
            run.bold = True


def generate_docx(context: dict[str, Any], review_type: str, output_path: Path) -> None:
    """Generate a Word .docx design-review document.

    Args:
        context: Same context dict passed to the Jinja2 template.
        review_type: "srr", "pdr", or "cdr".
        output_path: Where to write the .docx file.
    """
    doc = Document()

    # Title
    title = doc.add_heading(
        f"{review_type.upper()} — {context.get('mission_name', 'Mission')}",
        level=0,
    )
    doc.add_paragraph(f"Document Date: {context.get('date', '')}")
    doc.add_paragraph(f"Study: {context.get('study_name', '')}")
    doc.add_paragraph("Generated by: SpaceCDF AI Concurrent Design Facility")

    # 1. Executive Summary
    doc.add_heading("1. Executive Summary", level=1)
    doc.add_paragraph("[HUMAN INPUT REQUIRED: Executive summary narrative]")

    # 2. System Overview
    doc.add_heading("2. System Overview", level=1)
    doc.add_heading("2.1 Orbit", level=2)
    orbit = context.get("orbit", {}) or {}
    orbit_rows = [
        ("Orbit Type", str(orbit.get("orbit_type", "")).upper()),
        ("Altitude (km)", orbit.get("altitude_km", "")),
        ("Inclination (deg)", orbit.get("inclination_deg", "")),
        ("Period (min)", f"{orbit.get('period_min', 0) or 0:.1f}"),
        ("Eclipse Fraction", f"{orbit.get('eclipse_fraction', 0) or 0:.2f}"),
        ("Mission Duration (yr)", orbit.get("mission_duration_years", "")),
    ]
    t = doc.add_table(rows=len(orbit_rows), cols=2)
    t.style = "Light Grid"
    for i, (k, v) in enumerate(orbit_rows):
        t.rows[i].cells[0].text = str(k)
        t.rows[i].cells[1].text = str(v)

    doc.add_heading("2.2 Spacecraft", level=2)
    doc.add_paragraph(f"Mission Type: {context.get('mission_type', '')}")
    doc.add_paragraph(f"Spacecraft Class: {context.get('spacecraft_class', '')}")
    doc.add_paragraph(f"Number of Spacecraft: {context.get('num_spacecraft', 1)}")

    # 3. Mass Budget
    doc.add_heading("3. Mass Budget", level=1)
    _budget_table(doc, context.get("budgets", {}).get("mass", {}), "kg")

    # 4. Power Budget
    doc.add_heading("4. Power Budget", level=1)
    _budget_table(doc, context.get("budgets", {}).get("power", {}), "W")

    # 5. Data Budget
    doc.add_heading("5. Data Budget", level=1)
    data_budget = context.get("budgets", {}).get("data", {}) or {}
    lines = data_budget.get("lines", [])
    if lines:
        t = doc.add_table(rows=1, cols=4)
        t.style = "Light Grid"
        _add_header_row(t, ["Subsystem", "Source", "Value", "Unit"])
        for line in lines:
            row = t.add_row().cells
            row[0].text = str(line.get("subsystem", ""))
            row[1].text = str(line.get("equipment", ""))
            row[2].text = f"{line.get('nominal_value', 0):.2f}"
            row[3].text = str(line.get("unit", ""))
    else:
        doc.add_paragraph("No data budget available.")

    # 6. Cost Breakdown
    doc.add_heading("6. Cost Breakdown", level=1)
    cost = context.get("cost") or {}
    if cost:
        t = doc.add_table(rows=1, cols=2)
        t.style = "Light Grid"
        _add_header_row(t, ["Confidence Level", "Cost (MEUR)"])
        for label, key in [("P50", "p50_meur"), ("P70", "p70_meur"),
                           ("P80", "p80_meur"), ("P90", "p90_meur")]:
            row = t.add_row().cells
            row[0].text = label
            row[1].text = f"{cost.get(key, 0):.1f}"
        doc.add_paragraph(f"Model used: {cost.get('model_used', '')}")
        doc.add_paragraph(
            f"Total life-cycle cost: {cost.get('total_lcc_meur', 0):.1f} MEUR"
        )
    else:
        doc.add_paragraph("Cost estimation not available.")

    # 7. Compliance Matrix
    doc.add_heading("7. Compliance Matrix", level=1)
    compliance = context.get("compliance") or {}
    verifications = compliance.get("verifications", [])
    if verifications:
        t = doc.add_table(rows=1, cols=5)
        t.style = "Light Grid"
        _add_header_row(t, ["Req ID", "Description", "Achieved", "Margin %", "Status"])
        for v in verifications:
            row = t.add_row().cells
            row[0].text = str(v.get("requirement_id", ""))
            row[1].text = str(v.get("requirement_text", ""))
            av = v.get("achieved_value")
            row[2].text = f"{av:.2f}" if isinstance(av, (int, float)) else "—"
            mp = v.get("margin_percent")
            row[3].text = f"{mp:.1f}" if isinstance(mp, (int, float)) else "—"
            status = str(v.get("status", "")).lower()
            row[4].text = status.upper()
            colour = STATUS_COLOURS.get(status)
            if colour:
                _shade_cell(row[4], colour)
        doc.add_paragraph(
            f"Compliance: {compliance.get('compliant', 0)} / "
            f"{compliance.get('total_requirements', 0)} "
            f"({compliance.get('compliance_percent', 0):.1f}%)"
        )
    else:
        doc.add_paragraph("No compliance data available.")

    # 8. Equipment List
    doc.add_heading("8. Equipment List", level=1)
    equipment = context.get("equipment", [])
    if equipment:
        t = doc.add_table(rows=1, cols=5)
        t.style = "Light Grid"
        _add_header_row(t, ["Subsystem", "Parameter", "Component", "Manufacturer", "TRL"])
        for eq in equipment:
            row = t.add_row().cells
            row[0].text = str(eq.get("domain", ""))
            row[1].text = str(eq.get("parameter_id", ""))
            row[2].text = str(eq.get("equipment_name", ""))
            row[3].text = str(eq.get("manufacturer", ""))
            row[4].text = str(eq.get("trl", "—"))
    else:
        doc.add_paragraph("No equipment selected yet.")

    # 9. TRL Assessment
    doc.add_heading("9. TRL Assessment", level=1)
    trl_list = context.get("trl_assessments", [])
    if trl_list:
        t = doc.add_table(rows=1, cols=4)
        t.style = "Light Grid"
        _add_header_row(t, ["Subsystem", "Baseline (TRL)", "Innovation (TRL)", "Recommendation"])
        for trl in trl_list:
            row = t.add_row().cells
            row[0].text = str(trl.get("subsystem", ""))
            row[1].text = f"{trl.get('baseline_component', '')} ({trl.get('baseline_trl', '')})"
            innov = trl.get("innovation_component")
            row[2].text = f"{innov} ({trl.get('innovation_trl', '')})" if innov else "—"
            row[3].text = str(trl.get("recommendation", ""))
    else:
        doc.add_paragraph("[HUMAN INPUT REQUIRED: TRL assessment]")

    # PDR / CDR extras
    if review_type in ("pdr", "cdr"):
        doc.add_heading("10. Trade Studies", level=1)
        doc.add_paragraph(
            "[HUMAN INPUT REQUIRED: Summary of trade studies and rationale.]"
        )

        doc.add_heading("11. Risk Register", level=1)
        risks = context.get("risks", [])
        if risks:
            t = doc.add_table(rows=1, cols=2)
            t.style = "Light Grid"
            _add_header_row(t, ["#", "Risk"])
            for i, r in enumerate(risks, 1):
                row = t.add_row().cells
                row[0].text = str(i)
                row[1].text = str(r)
        else:
            doc.add_paragraph("[HUMAN INPUT REQUIRED: Risk register.]")

    if review_type == "cdr":
        doc.add_heading("12. Verification Test Plan", level=1)
        doc.add_paragraph(
            "[HUMAN INPUT REQUIRED: Model philosophy, qualification, acceptance tests.]"
        )

    doc.save(str(output_path))


def _budget_table(doc: Document, budget: dict, unit: str) -> None:
    lines = budget.get("lines", []) if isinstance(budget, dict) else []
    if not lines:
        doc.add_paragraph(f"No {unit} budget data available.")
        return
    t = doc.add_table(rows=1, cols=5)
    t.style = "Light Grid"
    _add_header_row(
        t,
        ["Subsystem", "Equipment", f"Nominal ({unit})", "Margin %", f"With Margin ({unit})"],
    )
    for line in lines:
        row = t.add_row().cells
        row[0].text = str(line.get("subsystem", ""))
        row[1].text = str(line.get("equipment", ""))
        nom = float(line.get("nominal_value", 0) or 0)
        margin = float(line.get("margin_percent", 0) or 0)
        row[2].text = f"{nom:.2f}"
        row[3].text = f"{margin:.0f}"
        row[4].text = f"{nom * (1 + margin / 100):.2f}"
    # Total row
    total_nom = float(budget.get("total_nominal", 0) or 0)
    total_margin = float(budget.get("total_with_margin", 0) or 0)
    row = t.add_row().cells
    row[0].text = "TOTAL"
    row[2].text = f"{total_nom:.2f}"
    row[4].text = f"{total_margin:.2f}"
    for c in row:
        for p in c.paragraphs:
            for r in p.runs:
                r.bold = True

    status = str(budget.get("status", "")).lower()
    colour = STATUS_COLOURS.get(status)
    mp = budget.get("margin_percent", 0) or 0
    p = doc.add_paragraph(
        f"Allocation: {budget.get('allocation', 0):.2f} {unit} — "
        f"Margin: {mp:.1f}% ({status.upper()})"
    )
    if colour:
        # Light emphasis via bold
        for run in p.runs:
            run.bold = True
