"""SpaceCDF — SMO Simulator Configuration Exporter.

Generates the complete config directory structure that the
SpaceMissionSimulation engine loads. Produces ~20 YAML files
from a converged DesignState.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from spacecdf_common.agents.base import DesignState
from spacecdf_common.models.study import MissionRequirements

from .orbit_gen import generate_orbit_yaml
from .param_id_allocator import ParamIDAllocator


@dataclass
class SMOExportResult:
    """Result of SMO config export."""
    files: dict[str, Any] = field(default_factory=dict)  # path -> yaml dict
    validation_errors: list[str] = field(default_factory=list)
    validation_warnings: list[str] = field(default_factory=list)
    param_id_map: dict[str, int] = field(default_factory=dict)

    @property
    def is_valid(self) -> bool:
        return len(self.validation_errors) == 0


class SMOExporter:
    """Exports SpaceCDF design state to SMO simulator configuration."""

    def __init__(self):
        self._allocator = ParamIDAllocator()

    def export(
        self,
        state: DesignState,
        requirements: MissionRequirements,
    ) -> SMOExportResult:
        """Generate complete SMO config from design state."""
        result = SMOExportResult()

        # Allocate parameter IDs
        self._allocator.allocate_from_state(state)
        result.param_id_map = dict(self._allocator._allocations)

        # Generate each config file
        result.files["mission.yaml"] = self._gen_mission(state, requirements)
        result.files["orbit.yaml"] = self._gen_orbit(state, requirements)

        # Subsystem configs
        result.files["subsystems/eps.yaml"] = self._gen_eps(state)
        result.files["subsystems/aocs.yaml"] = self._gen_aocs(state)
        result.files["subsystems/tcs.yaml"] = self._gen_tcs(state)
        result.files["subsystems/ttc.yaml"] = self._gen_ttc(state)
        result.files["subsystems/obdh.yaml"] = self._gen_obdh(state)
        result.files["subsystems/payload.yaml"] = self._gen_payload(state)
        result.files["subsystems/fdir.yaml"] = self._gen_fdir(state)

        # Telemetry
        result.files["telemetry/parameters.yaml"] = self._gen_parameters()
        result.files["telemetry/hk_structures.yaml"] = self._gen_hk_structures()

        # Monitoring
        result.files["monitoring/s12_definitions.yaml"] = self._gen_s12(state)
        result.files["monitoring/s19_rules.yaml"] = self._gen_s19()

        # Events and commands
        result.files["events/event_catalog.yaml"] = self._gen_events()
        result.files["commands/tc_catalog.yaml"] = self._gen_commands()

        # Planning
        result.files["planning/activity_types.yaml"] = self._gen_activities(state)

        # FDIR procedures
        for name, content in self._gen_fdir_procedures(state).items():
            result.files[f"fdir/procedures/{name}.yaml"] = content

        # MCS
        result.files["mcs/positions.yaml"] = self._gen_mcs_positions()

        # Validate cross-references
        self._validate(result)

        return result

    def export_to_disk(
        self,
        state: DesignState,
        requirements: MissionRequirements,
        output_dir: str | Path,
    ) -> SMOExportResult:
        """Export to disk as YAML files."""
        result = self.export(state, requirements)
        output_dir = Path(output_dir)

        for filepath, content in result.files.items():
            full_path = output_dir / filepath
            full_path.parent.mkdir(parents=True, exist_ok=True)
            with open(full_path, "w") as f:
                yaml.dump(content, f, default_flow_style=False, sort_keys=False)

        return result

    # --- Config generators ---

    def _gen_mission(self, state: DesignState, req: MissionRequirements) -> dict:
        return {
            "name": req.name,
            "description": f"Auto-generated by SpaceCDF for {req.name}",
            "spacecraft_apid": 0x01,
            "bootloader_apid": 0x02,
            "start_in_bootloader": True,
            "pus_version": 2,
            "time_epoch": "2000-01-01T12:00:00",
            "orbit": {
                "type": req.orbit.orbit_type,
                "altitude_km": req.orbit.altitude_km,
                "inclination_deg": req.orbit.inclination_deg,
            },
            "payload": {
                "type": req.payloads[0].type if req.payloads else "generic",
                "description": req.payloads[0].description if req.payloads else "",
            },
            "ground_segment": {
                "stations": req.ground_stations,
                "band": "X",
            },
            "network": {
                "tc_port": 8001,
                "tm_port": 8002,
                "instr_port": 8003,
                "http_port": 8080,
                "sim_tick_hz": 1.0,
                "tm_max_clients": 8,
            },
        }

    def _gen_orbit(self, state: DesignState, req: MissionRequirements) -> dict:
        # Look up ground stations from KB or use defaults
        gs_data = []
        gs_defaults = {
            "KSAT Svalbard": {"lat_deg": 78.229, "lon_deg": 15.407, "alt_km": 0.458},
            "KSAT Troll": {"lat_deg": -72.012, "lon_deg": 2.535, "alt_km": 1.275},
            "DSN Goldstone": {"lat_deg": 35.426, "lon_deg": -116.890, "alt_km": 1.0},
            "DSN Madrid": {"lat_deg": 40.431, "lon_deg": -4.249, "alt_km": 0.8},
            "DSN Canberra": {"lat_deg": -35.402, "lon_deg": 148.982, "alt_km": 0.7},
        }
        for gs_name in req.ground_stations:
            if gs_name in gs_defaults:
                gs_data.append({"name": gs_name, **gs_defaults[gs_name], "min_elevation_deg": 5.0})
            else:
                gs_data.append({"name": gs_name, "lat_deg": 78.23, "lon_deg": 15.41,
                                "alt_km": 0.0, "min_elevation_deg": 5.0})

        return generate_orbit_yaml(
            altitude_km=req.orbit.altitude_km,
            inclination_deg=req.orbit.inclination_deg,
            eccentricity=req.orbit.eccentricity,
            ground_stations=gs_data,
        )

    def _gen_eps(self, state: DesignState) -> dict:
        sa_area = state.get("power.sa_area_m2", 0.3) or 0.3
        bat_wh = state.get("power.battery_capacity_wh", 120) or 120
        platform_power = state.get("power.total_sunlight_w", 50) or 50

        return {
            "model": "eps_basic",
            "technology": "triple_junction_gaas",
            "arrays": [
                {"name": "A", "area_m2": round(sa_area / 2, 4), "efficiency": 0.295},
                {"name": "B", "area_m2": round(sa_area / 2, 4), "efficiency": 0.295},
            ],
            "battery": {
                "type": "li_ion",
                "capacity_wh": round(bat_wh, 1),
                "voltage_nom": 28.0 if bat_wh > 50 else 7.4,
                "soc_100_v": 29.2 if bat_wh > 50 else 8.4,
                "soc_0_v": 21.5 if bat_wh > 50 else 6.0,
                "internal_r_ohm": 0.05,
            },
            "platform_idle_power_w": round(platform_power * 0.6, 1),
            "payload_power_w": state.get("payload.0.power_w", 20) or 20,
            "payload_standby_power_w": 5.0,
            "fpa_cooler_power_w": 15.0,
            "transponder_power_w": state.get("link.ttc_power_w", 15) or 15,
            "transponder_rx_power_w": 5.0,
            "power_lines": {
                "obc": True, "ttc_rx": True, "ttc_tx": False,
                "payload": False, "fpa_cooler": False,
                "htr_bat": True, "htr_obc": True, "aocs_wheels": False,
            },
            "param_ids": self._allocator.get_subsystem_params("eps"),
        }

    def _gen_aocs(self, state: DesignState) -> dict:
        return {
            "model": "aocs_basic",
            "modes": ["nominal", "detumble", "safe", "wheel_desat", "slew"],
            "reaction_wheels": {
                "max_speed_rpm": 5500,
                "nominal_speed_rpm": 1200,
                "desaturation_speed_rpm": 200,
            },
            "num_wheels": 4,
            "attitude_error_deadband_deg": state.get("aocs.pointing_accuracy_deg", 0.1) or 0.1,
            "param_ids": self._allocator.get_subsystem_params("aocs"),
        }

    def _gen_tcs(self, state: DesignState) -> dict:
        heater_power = state.get("thermal.heater_power_w", 5) or 5
        return {
            "model": "tcs_basic",
            "zones": [
                {"name": "panel_px", "capacitance_j_per_c": 200, "time_constant_s": 600, "initial_temp_c": 15},
                {"name": "panel_mx", "capacitance_j_per_c": 200, "time_constant_s": 600, "initial_temp_c": 15},
                {"name": "panel_py", "capacitance_j_per_c": 200, "time_constant_s": 600, "initial_temp_c": 15},
                {"name": "panel_my", "capacitance_j_per_c": 200, "time_constant_s": 600, "initial_temp_c": 15},
                {"name": "panel_pz", "capacitance_j_per_c": 200, "time_constant_s": 600, "initial_temp_c": 15},
                {"name": "panel_mz", "capacitance_j_per_c": 200, "time_constant_s": 600, "initial_temp_c": 15},
                {"name": "obc", "capacitance_j_per_c": 50, "time_constant_s": 300, "initial_temp_c": 25},
                {"name": "battery", "capacitance_j_per_c": 100, "time_constant_s": 450, "initial_temp_c": 20},
                {"name": "fpa", "capacitance_j_per_c": 20, "time_constant_s": 120, "initial_temp_c": 20},
            ],
            "heaters": [
                {"name": "battery", "power_w": round(heater_power * 0.6, 1), "on_temp_c": 0, "off_temp_c": 10},
                {"name": "obc", "power_w": round(heater_power * 0.4, 1), "on_temp_c": -5, "off_temp_c": 5},
            ],
            "fpa_cooler_target_c": -5.0,
            "param_ids": self._allocator.get_subsystem_params("tcs"),
        }

    def _gen_ttc(self, state: DesignState) -> dict:
        return {
            "model": "ttc_basic",
            "ul_freq_mhz": 2025.0,
            "dl_freq_mhz": 8200.0,
            "tm_rate_hi_bps": int(state.get("link.downlink_rate_bps", 64000) or 64000),
            "tm_rate_lo_bps": 9600,
            "eirp_dbw": 0.0,
            "gs_g_t_db": 32.0,
            "sc_gain_dbi": 6.0,
            "param_ids": self._allocator.get_subsystem_params("ttc"),
        }

    def _gen_obdh(self, state: DesignState) -> dict:
        return {
            "model": "obdh_basic",
            "param_ids": self._allocator.get_subsystem_params("obdh"),
        }

    def _gen_payload(self, state: DesignState) -> dict:
        data_rate = state.get("payload.0.data_rate_mbps", 100) or 100
        return {
            "model": "payload_basic",
            "fpa_cooler_target_c": -5.0,
            "fpa_ambient_c": 20.0,
            "fpa_tau_cooling_s": 120.0,
            "fpa_tau_warming_s": 60.0,
            "fpa_cooler_power_w": 15.0,
            "image_size_mb": 800.0,
            "total_storage_mb": float(state.get("data.storage_required_gb", 20) or 20) * 1024,
            "line_rate_hz": 1000.0,
            "data_rate_mbps": data_rate,
            "param_ids": self._allocator.get_subsystem_params("payload"),
        }

    def _gen_fdir(self, state: DesignState) -> dict:
        rules = [
            {"parameter": "eps.bat_soc", "condition": "< 20", "threshold": 20, "level": 2,
             "action": "load_shed_stage1", "description": "Battery SOC critical"},
            {"parameter": "eps.bat_soc", "condition": "< 10", "threshold": 10, "level": 3,
             "action": "safe_mode_entry", "description": "Battery SOC emergency"},
            {"parameter": "aocs.att_error", "condition": "> 5", "threshold": 5, "level": 2,
             "action": "aocs_reset", "description": "Attitude error exceeds 5 deg"},
            {"parameter": "tcs.temp_battery", "condition": "> 45", "threshold": 45, "level": 2,
             "action": "load_shed_stage1", "description": "Battery temperature high"},
            {"parameter": "tcs.temp_battery", "condition": "< -10", "threshold": -10, "level": 2,
             "action": "htr_bat_on", "description": "Battery temperature low"},
        ]
        return {"enabled": True, "rules": rules}

    def _gen_parameters(self) -> dict:
        return {"parameters": self._allocator.param_defs}

    def _gen_hk_structures(self) -> dict:
        structures = []
        for subsys, sid, interval in [
            ("eps", 1, 1.0), ("aocs", 2, 4.0), ("tcs", 3, 60.0),
            ("obdh", 4, 8.0), ("ttc", 5, 8.0), ("payload", 6, 10.0),
        ]:
            params = []
            for pdef in self._allocator.param_defs:
                if pdef["subsystem"] == subsys:
                    params.append({
                        "param_id": pdef["id"],
                        "pack_format": "H",  # uint16 default
                        "scale": 100,
                    })
            if params:
                structures.append({
                    "sid": sid,
                    "name": subsys.upper(),
                    "interval_s": interval,
                    "parameters": params,
                })
        return {"structures": structures}

    def _gen_s12(self, state: DesignState) -> dict:
        defs = [
            {"param_id": 0x0101, "name": "bat_soc_low", "check_type": 0,
             "low_limit": 20.0, "high_limit": 100.0, "severity": "WARNING",
             "description": "Battery SOC below 20%"},
            {"param_id": 0x0101, "name": "bat_soc_critical", "check_type": 0,
             "low_limit": 10.0, "high_limit": 100.0, "severity": "ALARM",
             "description": "Battery SOC below 10%"},
            {"param_id": 0x0100, "name": "bus_voltage_range", "check_type": 0,
             "low_limit": 22.0, "high_limit": 34.0, "severity": "ALARM",
             "description": "Bus voltage out of range"},
            {"param_id": 0x020C, "name": "att_error_high", "check_type": 0,
             "low_limit": 0.0, "high_limit": 5.0, "severity": "WARNING",
             "description": "Attitude error exceeds 5 deg"},
            {"param_id": 0x0407, "name": "bat_temp_high", "check_type": 0,
             "low_limit": -10.0, "high_limit": 45.0, "severity": "ALARM",
             "description": "Battery temperature out of range"},
        ]
        return {"s12_definitions": defs}

    def _gen_s19(self) -> dict:
        rules = [
            {"ea_id": 1, "event_type": 0x0101, "action_func_id": 0x10,
             "description": "Undervoltage → load shed stage 1", "enabled": True},
            {"ea_id": 2, "event_type": 0x0102, "action_func_id": 0x20,
             "description": "Critical undervoltage → safe mode", "enabled": True},
            {"ea_id": 3, "event_type": 0x0201, "action_func_id": 0x30,
             "description": "AOCS error → AOCS reset", "enabled": True},
        ]
        return {"s19_rules": rules}

    def _gen_events(self) -> dict:
        events = [
            {"id": 0x0001, "name": "AOS", "severity": "INFO", "subsystem": "orbital",
             "description": "Acquisition of Signal"},
            {"id": 0x0002, "name": "LOS", "severity": "INFO", "subsystem": "orbital",
             "description": "Loss of Signal"},
            {"id": 0x0003, "name": "ECLIPSE_ENTRY", "severity": "INFO", "subsystem": "orbital",
             "description": "Spacecraft enters eclipse"},
            {"id": 0x0004, "name": "ECLIPSE_EXIT", "severity": "INFO", "subsystem": "orbital",
             "description": "Spacecraft exits eclipse"},
            {"id": 0x0101, "name": "EPS_UNDERVOLTAGE", "severity": "MEDIUM", "subsystem": "eps",
             "description": "Bus voltage below threshold"},
            {"id": 0x0102, "name": "EPS_CRITICAL_SOC", "severity": "HIGH", "subsystem": "eps",
             "description": "Battery SOC critically low"},
            {"id": 0x0201, "name": "AOCS_ERROR_HIGH", "severity": "MEDIUM", "subsystem": "aocs",
             "description": "Attitude error exceeds threshold"},
            {"id": 0x0401, "name": "TCS_TEMP_WARNING", "severity": "LOW", "subsystem": "tcs",
             "description": "Temperature warning threshold exceeded"},
            {"id": 0x0501, "name": "TTC_LINK_LOST", "severity": "MEDIUM", "subsystem": "ttc",
             "description": "Downlink signal lost"},
            {"id": 0x0601, "name": "PAYLOAD_ERROR", "severity": "LOW", "subsystem": "payload",
             "description": "Payload reported error"},
        ]
        return {"events": events}

    def _gen_commands(self) -> dict:
        commands = [
            {"service": 8, "subtype": 1, "func_id": 0x10, "description": "Load shed stage 1"},
            {"service": 8, "subtype": 1, "func_id": 0x11, "description": "Load shed stage 2"},
            {"service": 8, "subtype": 1, "func_id": 0x12, "description": "Load shed stage 3"},
            {"service": 8, "subtype": 1, "func_id": 0x20, "description": "Enter safe mode"},
            {"service": 8, "subtype": 1, "func_id": 0x21, "description": "Exit safe mode"},
            {"service": 8, "subtype": 1, "func_id": 0x30, "description": "AOCS reset"},
            {"service": 8, "subtype": 1, "func_id": 0x31, "description": "AOCS enter nominal"},
            {"service": 8, "subtype": 1, "func_id": 0x40, "description": "Payload on"},
            {"service": 8, "subtype": 1, "func_id": 0x41, "description": "Payload off"},
            {"service": 8, "subtype": 1, "func_id": 0x50, "description": "TX on"},
            {"service": 8, "subtype": 1, "func_id": 0x51, "description": "TX off"},
        ]
        return {"commands": commands}

    def _gen_activities(self, state: DesignState) -> dict:
        payload_power = state.get("payload.0.power_w", 30) or 30
        activities = [
            {
                "name": "imaging_pass",
                "description": "Payload imaging acquisition",
                "duration_s": 600, "min_duration_s": 120, "max_duration_s": 1800,
                "power_w": payload_power,
                "data_volume_mb": 800,
                "requires_attitude": "nominal",
                "requires_daylight": True, "requires_contact": False,
                "requires_subsystems": ["payload", "aocs"],
                "priority": "high",
                "conflicts_with": ["data_dump"],
            },
            {
                "name": "data_dump",
                "description": "Downlink stored data to ground station",
                "duration_s": 600, "min_duration_s": 120, "max_duration_s": 900,
                "power_w": state.get("link.ttc_power_w", 15) or 15,
                "data_volume_mb": 0,
                "requires_attitude": "nominal",
                "requires_daylight": False, "requires_contact": True,
                "requires_subsystems": ["ttc"],
                "priority": "high",
                "conflicts_with": ["imaging_pass"],
            },
            {
                "name": "calibration",
                "description": "Payload calibration sequence",
                "duration_s": 300, "min_duration_s": 120, "max_duration_s": 600,
                "power_w": payload_power * 0.5,
                "data_volume_mb": 100,
                "requires_attitude": "nominal",
                "requires_daylight": True, "requires_contact": False,
                "requires_subsystems": ["payload", "aocs"],
                "priority": "medium",
                "conflicts_with": [],
            },
        ]
        return {"activity_types": activities}

    def _gen_fdir_procedures(self, state: DesignState) -> dict[str, dict]:
        procedures = {}

        procedures["safe_mode_entry"] = {
            "procedure_id": "safe_mode_entry",
            "name": "Safe Mode Entry",
            "category": "fdir_response",
            "description": "Enter safe mode: payload off, AOCS safe, heaters standby",
            "steps": [
                {"step_id": 1, "name": "Payload off", "delay_s": 0,
                 "command": "s8_command", "params": {"func_id": 0x41, "data": []}},
                {"step_id": 2, "name": "AOCS safe mode", "delay_s": 2,
                 "command": "s8_command", "params": {"func_id": 0x30, "data": []}},
                {"step_id": 3, "name": "TX off", "delay_s": 2,
                 "command": "s8_command", "params": {"func_id": 0x51, "data": []}},
            ],
            "timeout_s": 30, "max_retries": 2,
        }

        procedures["load_shed_stage1"] = {
            "procedure_id": "load_shed_stage1",
            "name": "Load Shed Stage 1",
            "category": "fdir_response",
            "description": "Shed non-essential loads: payload off, FPA cooler off",
            "steps": [
                {"step_id": 1, "name": "Payload off", "delay_s": 0,
                 "command": "s8_command", "params": {"func_id": 0x41, "data": []}},
            ],
            "timeout_s": 10, "max_retries": 1,
        }

        procedures["aocs_reset"] = {
            "procedure_id": "aocs_reset",
            "name": "AOCS Reset",
            "category": "fdir_response",
            "description": "Reset AOCS to detumble mode and re-acquire attitude",
            "steps": [
                {"step_id": 1, "name": "AOCS reset", "delay_s": 0,
                 "command": "s8_command", "params": {"func_id": 0x30, "data": []}},
            ],
            "timeout_s": 120, "max_retries": 3,
        }

        return procedures

    def _gen_mcs_positions(self) -> dict:
        return {
            "positions": [
                {"name": "Flight Director", "subsystems": ["all"]},
                {"name": "Power Officer", "subsystems": ["eps"]},
                {"name": "AOCS Officer", "subsystems": ["aocs"]},
                {"name": "Thermal Officer", "subsystems": ["tcs"]},
                {"name": "Comms Officer", "subsystems": ["ttc"]},
                {"name": "Payload Manager", "subsystems": ["payload"]},
            ]
        }

    def _validate(self, result: SMOExportResult) -> None:
        """Run cross-reference validation checks."""
        params_yaml = result.files.get("telemetry/parameters.yaml", {})
        param_ids = {p["id"] for p in params_yaml.get("parameters", [])}

        # Check HK structures reference valid param_ids
        hk = result.files.get("telemetry/hk_structures.yaml", {})
        for struct in hk.get("structures", []):
            for p in struct.get("parameters", []):
                if p["param_id"] not in param_ids:
                    result.validation_errors.append(
                        f"HK SID {struct['sid']}: param_id 0x{p['param_id']:04X} not in parameters.yaml"
                    )

        # Check S12 references valid param_ids
        s12 = result.files.get("monitoring/s12_definitions.yaml", {})
        for rule in s12.get("s12_definitions", []):
            if rule["param_id"] not in param_ids:
                result.validation_warnings.append(
                    f"S12 rule '{rule['name']}': param_id 0x{rule['param_id']:04X} not in parameters.yaml"
                )

        # Check param ID range overlaps
        ranges: dict[str, list[int]] = {}
        for pdef in params_yaml.get("parameters", []):
            subsys = pdef.get("subsystem", "unknown")
            ranges.setdefault(subsys, []).append(pdef["id"])
        for subsys, ids in ranges.items():
            if ids:
                id_min, id_max = min(ids), max(ids)
                for other_subsys, other_ids in ranges.items():
                    if other_subsys != subsys and other_ids:
                        other_min, other_max = min(other_ids), max(other_ids)
                        if id_min <= other_max and other_min <= id_max:
                            result.validation_warnings.append(
                                f"Param ID ranges overlap: {subsys} (0x{id_min:04X}-0x{id_max:04X}) "
                                f"and {other_subsys} (0x{other_min:04X}-0x{other_max:04X})"
                            )
